### ISSUE TITLE
Provided Framework configuration doesn't work

### ISSUE THREAD

**Issue by aalinia** [aik099/PhpStormProtocol#12]
I'm using:
* PhpStorm 9.0
* Symfony 2.7.3

Installed successfully but it doesn't work with `pstorm://open/?url=file://%f&line=%l`(based on the documentation).
Changed it to `pstorm://open/?url=file://%%f&line=%%l` and it worked. Does the documentation need to get updated or I'm missing something?

**Comment by aik099** [comment]
Please explain where have you put `storm://open/?url=file://%f&line=%l` in the Symfony application?

I'm suspecting that for Symfony `%` sign is used differently and you need to escape it (by repeating it twice). I've seen people using `PhpStormProtocol` with Nette and no escaping was needed, so documentation is fine. Maybe the sub-section needs to be added, that for Symfony `%%` must be used.

**Comment by aalinia** [comment]
I'm using it like this:
```
# app/config/config_dev.yml
framework:
    ide: "pstorm://open/?url=file://%%f&line=%%l"
```

Yeah, that makes sense. I have reached this tool from the Symfony documentation and that's why I thought that should work for Symfony as is.

Thanks.

**Comment by Rvanlaak** [comment]
Did follow your issue about vagrant, we have something related over here because project isn't hosted on the developer's client either. We get the following exception in PHPStorm:

    Cannot find file 'C:\Program Files (x86)\Google\Chrome\Application\45.0.2454.93\var\www\project\vendor\lexik\form-filter-bundle\Lexik\Bundle\FormFilterBundle\Event\Subscriber\AbstractDoctrineSubscriber.php'

**Comment by aik099** [comment]
The ideal way would be so teach Symfony to replace paths in file links for PhpStorm to have proper directories in them. If that's not possible you can do some JS replace magic in hook code provided in the library.

**Comment by Rvanlaak** [comment]
A snippet for that in [README.md](https://github.com/aik099/PhpStormProtocol#installing-on-windows) would be awesome!

My filepath (eg. /var/www/project/vendor) should be renamed to my network share (eg. P:\project\vendor).

An extra config parameter in `run_editor.js` to solve this would be nice.

**Comment by aik099** [comment]
Sure. Feel free to submit the PR. As I'm Mac user I don't a way to test the `run_editor.js` changes, but you can test them in real time.

**Comment by Rvanlaak** [comment]
:+1: see #14
