### ISSUE TITLE
Windows 10 - No error but file is not open

### ISSUE THREAD

**Issue by Snowbaha** [aik099/PhpStormProtocol#24]
Hello,

I am running the script with  Windows 10 (FR) 64 bits and PHPstorm 2017.

I adapt the reg with : 
`[HKEY_CLASSES_ROOT\phpstorm\shell\open\command]
@="wscript \"C:\\Program Files (x86)\\PhpStorm Protocol (Win)\\run_editor.js\" \"%1\""`

and the JS with : 

```
var settings = {
	// Set to 'true' (without quotes) if run on Windows 64bit. Set to 'false' (without quotes) otherwise.
	x64: false,

	// Set to folder name, where PhpStorm was installed to (e.g. 'PhpStorm')
	folder_name: 'PhpStorm 2016.3',

	// Set to window title (only text after dash sign), that you see, when switching to running PhpStorm instance
	window_title: 'PhpStorm 2017.1.3',

	// In case your file is mapped via a network share and paths do not match.
	// eg. /var/www will can replaced with Y:/
	projects_basepath: '',
	projects_path_alias: ''
};

// dont change anything below this line, unless you know what youre doing
var	url = WScript.Arguments(0),
	match = /^phpstorm:\/\/open\?(url=file:\/\/|file=)(.+)&line=(\d+)$/.exec(url),
	project = '',
	editor = '"C:\\' + (settings.x64 ? 'Program Files (x86)' : 'Program Files') + '\\JetBrains\\' + settings.folder_name + '\\bin\\

>phpstorm.exe

"';
```

But It does not work and I have no errors : 
Image demo : I clicked on the Controller file : https://vgy.me/OiVhlQ.png
Open with the script : https://vgy.me/jBi1Hk.png
...And nothing happen :(

Edit :  
On my config.yml I wrote : `ide: 'phpstorm://open?url=file://%%f&line=%%l' `

**Comment by aik099** [comment]
Are you using the latest codebase (from `master` branch) of this project? I'm asking because there were Windows 10 related fixes recently.

**Comment by Snowbaha** [comment]
To be sure, I copied all the code there : 
https://github.com/aik099/PhpStormProtocol/blob/master/PhpStorm%20Protocol%20(Win)/run_editor.js

So yes, it is the latest

**Comment by aik099** [comment]
Then I have no idea unfortunately. I know it worked in Windows 7, where I originally tested it upon and some fixes were applied to work on Windows 8 as well.

If you find out what causing it to malfunction, then PR would be welcome.

**Comment by Snowbaha** [comment]
Ok, do you know how I can have a log or something to help me to know that is wrong?

**Comment by aik099** [comment]
No idea. Probably there are some methods on `WScript.` object that can be used. The Google/MSDN would know better.

**Comment by buddh4** [comment]
Same issue here, I had to align the url a bit:

```
phpstorm://open/?file={file}&line={line}
```

note the additional `/` after open

**Comment by aik099** [comment]
So if you change `phpstorm://open?file={file}&line={line}` with `phpstorm://open/?file={file}&line={line}` in code, that is building links for you (not this protocol listener project), then it works for you?

**Comment by buddh4** [comment]
Yes, otherwise the [regex](https://github.com/asika32764/PhpStormProtocol/blob/da0116f90b52a89c57613f525ba097161a0a1d7b/PhpStorm%20Protocol%20(Win)/run_editor.js#L20) does not match and the scripts exits without any errors

```
/^phpstorm:\/\/open\/\?(url=file:\/\/|file=)(.+)&line=(\d+)$/
```

**Comment by aik099** [comment]
@buddh4 , please post actual link you click on Windows. I want to see how the path with all slashes looks like in there.

**Comment by aik099** [comment]
Ha, it looks like change made in #25 replaced regex by making `/` after `open` a requirement. Before it wasn't needed at all. And now URL in README.md doesn't actually work :(

**Comment by aik099** [comment]
What if you use `phpstorm://` link as in README.md (no `/` after `open`) and change regular expression in `run_editor.js` file from `/^phpstorm:\/\/open\/\?(url=file:\/\/|file=)(.+)&line=(\d+)$/` to `/^phpstorm:\/\/open\/?\?(url=file:\/\/|file=)(.+)&line=(\d+)$/` (replaced `open\/` with `open\/?`)?

Will it work then as well?

**Comment by Filoz** [comment]
for me the #25 is working on win 10 without adding a '/'

the only edit I made was about the exe path, because I'm using Jetbrains Toolbox

**Comment by aik099** [comment]
Nice to know. Then I'm closing this because changing binary path in config solves the problem.

**Comment by Snowbaha** [comment]
Hello, 
I did the change with
` (replaced open\/ with open\/?) `
in the run_editor.js

But Now I have this error : https://vgy.me/2XLWSN.png

Is it the same issue or another one?

**Comment by aik099** [comment]
I don't know, I can't easily translate French text on the images 😉

**Comment by Snowbaha** [comment]
Oups sorry : 
"Line : 55"
Char (not sure what it is?) : 2
Error : File is not found

**Comment by aik099** [comment]
I have no idea. Probably something in regexp needs to be escaped differently.

**Comment by Snowbaha** [comment]
Ok not easy to find indeed :(

**Comment by buddh4** [comment]
Perhaps you have to align the `editor` path. Try setting the path directly

```
editor = "<path to my phpstorm.exe>";
```

instead of

```
editor = '"C:\\' + (settings.x64 ? 'Program Files (x86)' : 'Program Files') + '\\JetBrains\\' + settings.folder_name + '\\bin\\phpstorm.exe"';
```

**Comment by Snowbaha** [comment]
Ohhh nice ! It is working ^^
Thanks !

`editor = '"C:\\Program Files (x86)\\JetBrains\\' + settings.folder_name + '\\bin\\phpstorm.exe"';`

**Comment by aik099** [comment]
@Snowbaha , were you able to fix the regexp and ready to send a PR?

**Comment by Snowbaha** [comment]
Ok i will Try, I found the right editor path ^^ the x64 was inversed
