### ISSUE TITLE
got an error while opening file

### ISSUE THREAD

**Issue by strafun** [aik099/PhpStormProtocol#27]
Hello, i try to install it on windows 10.
When i opens my file with link phpstorm://open?url=C:/OpenServer/domains/.../BlogPosts.php&line=357 
Got an error: Windows Script Host - there is no script engine for file extension ".js".
i changed settings in js file - what i miss?
Thanks.

**Comment by aik099** [comment]
Probably something is missing because when `phpstorm://` protocol handler is used the associated `run_script.js` can't be executed. I had reports that in general it works without issues on Windows 10.

If you find out what is it, then please update README with relevant installation instructions.

**Comment by OAPrilepa** [comment]
https://www.inflectra.com/support/knowledgebase/kb58.aspx

**Comment by aik099** [comment]
@OAPrilepa , thanks for the info. Would you mind making PR to the README.md explaining the fix (not all that long history on referenced page) with a link to that page for more info.

**Comment by codingjungle** [comment]
I had this issue too, i followed this guide:

http://www.winhelponline.com/blog/error-there-is-no-script-engine-for-file-extension-when-running-js-files/

it is more intuitive, and easier to follow than the kb.
