### ISSUE TITLE
It work but with error

### ISSUE THREAD

**Issue by hooman-pro** [aik099/PhpStormProtocol#34]
when i click on link this box show:
![image](https://user-images.githubusercontent.com/11981070/99565839-60012400-29e1-11eb-9245-082ad718fa4f.png)
 
and after choice first option do  noting.
but when i add phpstormX64 from path as secound options and click on it show this error:

![image](https://user-images.githubusercontent.com/11981070/99565635-1f090f80-29e1-11eb-9938-4738937e4281.png)

it is only work in firefox and show this error!

**Comment by hooman-pro** [comment]
it solved.
my link was wrong and after url i miss file://

**Comment by aik099** [comment]
Thanks for the bug report. This issue will be useful for other people having a similar problem.
