### ISSUE TITLE
Please add to urldecode for linux

### ISSUE THREAD

**Issue by Karsi482** [aik099/PhpStormProtocol#42]
links in the browser are encoded like this:

```
phpstorm://open?file=%2Fmedia%2Fphantom%2FStorage%2FProjects%2FE-cabinet%2FE-cabinet%2Fapp%2FHttp%2FInterfaces%2FApi1CSoap.php&line=21
```

The PhpStorm opens them as a file without decoding the characters `%2F` thus it turns out that the program opens a file named

```
%2Fmedia%2Fphantom%2FStorage%2FProjects%2FE-cabinet%2FE-cabinet%2Fapp%2FHttp%2FInterfaces%2FApi1CSoap.php
```

**Comment by codingjungle** [comment]
I've added this into my fork of this app:
https://github.com/codingjungle/phpstorm-url-handler

**Comment by aik099** [comment]
@Karsi482 / @codingjungle  , please open a PR so that other Linux users could benefit from this change.
