### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by simeonbugarija** [aik099/PhpStormProtocol#45]
Hello,

I followed the instructions for Windows but for some reason it's not working.

I'm working on Windows 10 and I'm using Laravel 9 which generates the following link on the error page:

phpstorm://open?file=C%3A%5Claragon%5Cwww%5Claravel9%5Croutes%5Cweb.php&line=17

![image](https://user-images.githubusercontent.com/10814563/156923781-68f3f462-7f0a-4008-ad22-e0354496f80b.png)

What do I need to do in order to make this work?

**Comment by codingjungle** [comment]
https://www.winhelponline.com/blog/error-there-is-no-script-engine-for-file-extension-when-running-js-files/

this will take care of the issue.

**Comment by johnef** [comment]
@simeonbugarija how you solved this issue?

**Comment by simeonbugarija** [comment]
I didn't manage to make this work
