### ISSUE TITLE
JetBrains toolbox dir

### ISSUE THREAD

**Issue by KamilPesek** [aik099/PhpStormProtocol#46]
Do you have some details about Toolbox dir? For my environment, I had to change 
`\\JetBrains\\Toolbox\\apps\\PhpStorm\\ch-0` to `ch-1`. 
`ch-1` folder is the only one I have there. I did not find any information for this. 

Do you think I am "unusual case" or should we create some PR for this (add new param to configuration)? The problem is that I do not know how to easily get information about Jetbrains folder structure and what's the logic behind it.

PR could be like: https://gist.github.com/KamilPesek/e0447004a0cd75534836eca0ef242cbd

**Comment by aik099** [comment]
What is the OS name and version you're using?

**Comment by KamilPesek** [comment]
I am on Microsoft Windows 10 Pro, 10.0.19044 Build 19044.

When I searched for details I could see some people have also other dirs like `ch-8`, `ch-9`  (basically anything like `ch-[0-9] `) and other question also is what to do if there will be multiple folders.

**Comment by aik099** [comment]
Until we know what these folders mean (from JetBrains team) we can't say for sure.

Probably you can ask on the https://toolbox-support.jetbrains.com/hc/en-us/articles/115000978804-Where-are-the-IDEs-located-on-my-hard-drive- page about that.

**Comment by aik099** [comment]
I've posted a question on https://toolbox-support.jetbrains.com/hc/en-us/articles/115000978804?page=1#comment_5921213344530 .

**Comment by aik099** [comment]
@KamilPesek , good news. I've got a response on that forum (see the link above), that confirms your original suggestion. Please send a PR, but rename `toolbox_phpstorm_dir` variable into `toolbox_update_channel_dir`.

**Comment by KamilPesek** [comment]
> @KamilPesek , good news. I've got a response on that forum (see the link above), that confirms your original suggestion. Please send a PR, but rename `toolbox_phpstorm_dir` variable into `toolbox_update_channel_dir`.

Sure, no prob https://github.com/aik099/PhpStormProtocol/pull/47

**Comment by aik099** [comment]
Closed via #47.
