### ISSUE TITLE
can't find run_editor.js

### ISSUE THREAD

**Issue by yangweijie** [aik099/PhpStormProtocol#49]
![image](https://user-images.githubusercontent.com/1614114/234749207-ea9d1bf6-c4ef-4d8e-8a68-1af7855ce213.png)

![image](https://user-images.githubusercontent.com/1614114/234749268-cb6640fe-ff11-4efa-9dfb-36395e26fd38.png)

**Comment by aik099** [comment]
Looking at the screenshot I can tell, that you've copied over contents from https://github.com/aik099/PhpStormProtocol/tree/master/PhpStorm%20Protocol%20(Win) folder directly to the `C:\Program Files\` folder. That is incorrect.

You should copy https://github.com/aik099/PhpStormProtocol/tree/master/PhpStorm%20Protocol%20(Win) folder itself into `C:\Program Files\` so at the end you'll have a `C:\Program Files\PhpStorm Protocol (Win)` folder and any further actions should happen in there.

**Comment by yangweijie** [comment]
Yes, the reason for pop occus is the wrong path of run_editor.js. But for `phpstorm://open?file=%file&line=%line`  format , Your regexp is not suitable.
So i rewrite the script for myself.

~~~
var settings = {
    bin_path: "D:\\Program Files\\JetBrains\\PhpStorm 2022.3.2\\bin\\phpstorm64.exe ",
    window_title: 'PhpStorm'
};
var url = decodeURIComponent(WScript.Arguments(0));
//WScript.Echo(url);
if(url.indexOf('phpstorm') != -1){
	var line = url.substring(url.indexOf('&line=')+6);
	url = url.substring(url.indexOf('file='));
	var file = url.substring(url.indexOf('file=')+5, url.indexOf('&'));
	var editor = settings.bin_path+'--line %line% "%file%"';
	var command = editor.replace(/%line%/g, line)
        .replace(/%file%/g, file)
        .replace(/\//g, '\\');
    //WScript.Echo(command);
    var shell = new ActiveXObject('WScript.Shell');
    shell.Exec(command);
    shell.AppActivate(settings.window_title);
}else{
	WScript.Echo(url.indexOf('错误的url协议'));
}
~~~
Which is less complex and  works ok.
