### ISSUE TITLE
wsl + docker + win10 problem

### ISSUE THREAD

**Issue by vladimirbalin** [aik099/PhpStormProtocol#51]
I use sail - docker + win10(wsl) in my laravel project. My projects dir is "\\wsl$\Ubuntu\home\vladimirb\projects\"
base exception link: 
```
phpstorm://open?file=%2Fhome%2Fvladimirb%2Fprojects%2Flearn%2Fe-com-laravel%2Fresources%2Fviews%2Fwelcome.blade.php&line=20
```
and it opens well when i manually type in browsers url line: 
```
phpstorm://open?file=\\wsl$\Ubuntu\%2Fhome%2Fvladimirb%2Fprojects%2Flearn%2Fe-com-laravel%2Fresources%2Fviews%2Fwelcome.blade.php&line=20
```
My question is: what should i use here in cfg file:
```   
 // In case your file is mapped via a network share and paths do not match.
 // eg. /var/www will can replaced with Y:/
    projects_basepath: '',
    projects_path_alias: '',
```

?

**Comment by aik099** [comment]
@vladimirbalin , I can't give you an exact answer, because I don't know the path to files inside a Docker, but here is an example, that might help:

1. GuestOS (where a Web Server runs) has a PHP file at "/home/dev/sites/index.php"
2. HostOS (where Virtual Machine with GuestOS runs on) accesses that file via "C:\Users\your_username\Documents\sites\index.php"
3. You'll need this config:
```
projects_basepath: '/home/dev/',
projects_path_alias: 'C:/Users/your_username/Documents/',
```

Hope that helps.

**Comment by vladimirbalin** [comment]
Guest OS Docker path: 
```
/var/www/html/public/index.php
```

HostOS path of the same file:
```
\\wsl.localhost\Ubuntu\home\vladimirb\projects\learn\e-com-laravel\public\index.php
```

Tried some of combination but still dont get it

**Comment by aik099** [comment]
Do you have only 1 project on the Docker VM?

If that is so, then the following configuration would do the trick:
```
projects_basepath: '/var/www/html/public/',
projects_path_alias: '\\wsl.localhost\Ubuntu\home\vladimirb\projects\learn\e-com-laravel\public\',
```

Is the `\\wsl.localhost\Ubuntu\` a network mount on MS Windows?

**Comment by vladimirbalin** [comment]
> Do you have only 1 project on the Docker VM?
> 
> If that is so, then the following configuration would do the trick:
> 
> ```
> projects_basepath: '/var/www/html/public/',
> projects_path_alias: '\\wsl.localhost\Ubuntu\home\vladimirb\projects\learn\e-com-laravel\public\',
> ```
> 
> Is the `\\wsl.localhost\Ubuntu\` a network mount on MS Windows?

1. Yes, at once it only runs 1 project
2. Yes, bassically its kind of a network mount on Win 10

**Comment by aik099** [comment]
You need to debug it somehow (maybe using MsgBox or real-time debugging if such exists):
* what URL comes in
* what URL comes out
* what gets replaced to what

Probably it has something to do with `$` in URL.

**Comment by vladimirbalin** [comment]
![Screenshot_2](https://github.com/aik099/PhpStormProtocol/assets/58903037/eaa78c75-cb96-4708-9145-d6892a0e7024)
![Screenshot_1](https://github.com/aik099/PhpStormProtocol/assets/58903037/610a2103-c3d9-4712-8fbf-2dfe36943267)

I think problem that id doesnt replace anything in file variable

**Comment by vladimirbalin** [comment]
Ok, hardcoded like this, it finally works. Pretty dirty solution, gonna check little later and will comment here.
![Screenshot_3](https://github.com/aik099/PhpStormProtocol/assets/58903037/acc20771-ea32-4b02-b46d-ef73b81e6f33)

**Comment by vladimirbalin** [comment]
We were need to replace(actually just add to start of the line) first '/' with the '//wsl$/Ubuntu', so we need to do like this:

```
projects_basepath: '/',
projects_path_alias: '//wsl$/Ubuntu/',
```
