### ISSUE TITLE
Using Jetbrains Toolbox alias (enhancement)

### ISSUE THREAD

**Issue by Bozzified** [aik099/PhpStormProtocol#57]
I just wanted to say thanks for this because it works great now with Laravel Herd to launch PHPStorm.

However, as the version of PHPStorm are changing fairly frequently I would like to suggest to modify the script to just use the Jetbrain Toolbox alias/shell script name feature which resolves the PHPStorm version in use based on Toolbox selection.

I simply changed these 2 lines in my case:

Line 213 (run_editor.js)
```
editor = '"' + toolboxDirectory + settings.folder_name + '\\' + productVersion.launch[ 0 ].launcherPath.replace(/\//g, '\\') + '"';
```
to
```
editor = 'pstorm';
```
and

Line 100 (run_editor.js)
```
defaultCommandPath = settings.disk_letter + '\\' + ( settings.x64 ? 'Program Files' : 'Program Files (x86)' ) + '\\JetBrains\\' + settings.folder_name + ( settings.x64 ? '\\bin\\phpstorm64.exe' : '\\bin\\phpstorm.exe' );
```
to
```
defaultCommandPath = settings.disk_letter + '\\' + ( settings.x64 ? 'Program Files' : 'Program Files (x86)' ) + '\\JetBrains\\' + settings.folder_name + ( settings.x64 ? '\\bin\\phpstorm64.exe' : '\\bin\\phpstorm.exe' );
```
defaultCommandPath = 'pstorm';

as a dirty simplification. Then in Jetbrains Toolbox I just added "pstorm" as shell script

![image](https://github.com/user-attachments/assets/0b9f7ecb-df0d-4a23-8ee2-1f743226aa10)

works like a charm.

**Comment by aik099** [comment]
Does the PhpStorm window auto-activate, when using `phpstorm://` link in the Web Browser as well?

**Comment by Bozzified** [comment]
> @Bozzified , Does the PhpStorm window auto-activate, when using `phpstorm://` link in the Web Browser as well?

I think it does.. Laravel Herd is how I found out about your repo as it won't work to open the active site for dev in the PHPStorm if I didn't use your script.

So I tried this in url:

```phpstorm://open?url=file:///C:/Users/Bozzified/test.json```

It shows Microsoft Windowed Script Host dialog with "Open Windows Based Script Host" and when I click Open on that it launches PHPStorm. However, I think I probably removed a bunch of stuff where you regex stuff for filename or something to identify the target file the protocol url because it opens PHPStorm and my last project but doesn't open the file above.

So it kind of works, I just think I took out too much from your editor lines so it just probably starts phpstorm for any link.

I guess I was trying to get with pstorm alias from Toolbox was not to worry about Jetbrains updating PHPStorm every like month and me having to go constantly changing the script with proper PHPStorm version. So in that regard it works and gets triggered from phpstorm:// but I'm just missing the filename being passed in.

**Comment by aik099** [comment]
What if you run `pstorm path_to_file`. Does it activate PhpStorm window as well?

**Comment by Bozzified** [comment]
yeah it works fine like this and opens up the file:

```pstorm C:\Users\Bozzified\test.json```

**Comment by aik099** [comment]
> ... However, I think I probably removed a bunch of stuff where you regex stuff for filename or something to identify the target file the protocol url because it opens PHPStorm and my last project but doesn't open the file above.

The `phpstorm://` links should have an absolute file path on the local machine specified. Doesn't this work with Laravel Herd?

> So it kind of works, I just think I took out too much from your editor lines so it just probably starts phpstorm for any link.

Could you please be more specific (what you removed and why it caused problems)?

> I guess I was trying to get with pstorm alias from Toolbox was not to worry about Jetbrains updating PHPStorm every like month and me having to go constantly changing the script with proper PHPStorm version.

That's why the `settings.toolBoxActive` setting is there that automatically detects the current PhpStorm version from the JetBrains Toolbox. Why do you specify PhpStorm manually, when using JetBrains Toolbox?

**Comment by Bozzified** [comment]
> > ... However, I think I probably removed a bunch of stuff where you regex stuff for filename or something to identify the target file the protocol url because it opens PHPStorm and my last project but doesn't open the file above.
> 
> The `phpstorm://` links should have an absolute file path on the local machine specified. Doesn't this work with Laravel Herd?...
>

Yeah you are right.. but I just read your instructions really so I followed that.. and in it it's mentioned to define the folder path for PHPStorm version.

Should that just be left empty? and not modify anything else?

**Comment by Bozzified** [comment]
Okay.. i reverted back to your original unmodified run_editor.js and left folder_name empty and it works. I guess we can close this.

**Comment by Bozzified** [comment]
there was no need to point to pstorm at all and modify the script. If using Jetbrains Toolbox omitting the folder_name and leaving it empty will pick up latest PHPStorm version from Toolbox. So this was just me not understanding how it works.

**Comment by aik099** [comment]
> Should the PHPStorm version just be left empty under folder_name if I'm using Toolbox? and not modify anything else?

Yes.

**Comment by aik099** [comment]
I've made https://github.com/aik099/PhpStormProtocol/pull/58 based on your suggestions. It uses JetBrains ToolBox Shell Script (the `phpstorm`), when available instead of guessing latest PhpStorm installation/PhpStorm window name by itself. Theoretically should work faster.

@Bozzified , Could you please check if that works for you.?

P.S.
I've also added explanatory comments before settings, that shouldn't be changed, when using JetBrains Toolbox.

**Comment by aik099** [comment]
Please, with that PR, also check:
* if opening file at specific line works correctly (not only file is opened, but that line is also focused)
* if opening a folder works
.
