### ISSUE TITLE
Can open file in PHPStrom8

### ISSUE THREAD

**Issue by Nyholm** [aik099/PhpStormProtocol#7]
I just updated to PHPStorm8. 
The command `/usr/local/bin/pstorm [file]:[line]` does not really do its job. Nothing happens. Is this something you know about? Am I doing something wrong? Should I contact Jetbrains instead?

**Comment by aik099** [comment]
What is your OS?

**Comment by aik099** [comment]
If it's OSX, then you're in luck because PhpStorm have native url handler there since 8.x release. Just use `phpstorm://` protocol in url.

**Comment by Nyholm** [comment]
Sorry, OSX mavericks. But I'm afraid I'm not feeling that lucky. I've tried the phpstorm:// protocol as well but it does not do any better. The IDE becomes the active window but it does not open the correct file as before in PHPStorm7

**Comment by aik099** [comment]
The format you should be using is `phpstorm://open?file=%F&line=%L` (according to PhpStorm docs). I bet you're using `phpstorm://open/?url=file://%f&line=%l`.

**Comment by Nyholm** [comment]
Thank you! I don't know what i messed up.. Anyhow. It is working now. 
Btw. The format for PHPStorm protocol should be `phpstorm://open?file=%f&line=%l` (not with capital F and L)

**Comment by aik099** [comment]
Thanks. I've updated the README.md to indicate that.
